version: '3.8'

services:
  cosmos:
    image: fortizpenaloza/cosmos:latest
    ports:
      - "8090:8090" 
    volumes:
      - ./logs:/opt/cosmos/logs
    environment:
      PORT: "8090"
      ALLOWED_ORIGINS: "http://localhost:7080"

  telescope:
    image: jnahas/cosmos-ui:latest
    ports: 
      - "7080:80"
