version: '3.8'

services:
  cosmos:
    image: fortizpenaloza/cosmos:latest
    ports:
      - "8090:8090" 
    volumes:
      - ./logs:/opt/cosmos/logs

  telescope:
    image: jnahas/cosmos-ui:latest
    ports: 
      - "80:80"
